apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: homesync-poc-token-12345
    jsonData:
      version: Flux
      organization: homesync
      defaultBucket: poc_telemetry
      tlsSkipVerify: true
