name: homesync_poc
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # UI
  flutter_switch: ^0.3.2
  shimmer: ^3.0.0
  fl_chart: ^0.66.0
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/custom.ttf
